# Change these first
owner: ernawati12968
repo: uptime

sites:
  - name: WANA - 154.90.49.70
    url: https://154.90.49.70
  - name: HX - 45.77.39.110
    url: https://45.77.39.110
  - name: LND - 172.105.120.84
    url: http://172.105.120.84
  - name: DO - 206.189.38.181
    url: http://206.189.38.181
  - name: BETA - 45.76.178.167
    url: https://45.76.178.167
  - name: LUCKYSPIN - 45.76.146.115
    url: http://45.76.146.115
  - name: LINKMU - 149.28.146.122
    url: https://linkmu.cyou
  - name: DOM SMPH - 149.28.171.44
    url: http://149.28.171.44
  - name: DOM DJARUM - 67.219.103.227
    url: https://67.219.103.227
  - name: BETA2 - 45.77.251.235
    url: http://45.77.251.235:303/
  - name: RBS2 - 66.42.60.36
    url: https://66.42.60.36
  - name: PANEN2 - 45.77.170.187
    url: https://45.77.170.187
 - name: WANA1 - 45.32.123.103
    url: https://45.32.123.103
 - name: RTP - 45.76.179.228
    url: https://45.76.179.228
 - name: PANEN1 - 67.219.101.147
    url: https://67.219.101.147
 - name: BARONG - 67.219.102.118
    url: https://67.219.102.118
 - name: NUSA2 - 66.42.54.216
    url: https://66.42.54.216
 - name: BETA3 - 149.28.147.18
    url: https://149.28.147.18
 - name: ASGOL - 149.28.152.196
    url: https://149.28.152.196
 - name: SERVER GCR - 104.156.232.87
    url: https://104.156.232.87
 - name: RBS - 45.76.156.44
    url: https://45.76.156.44
 - name: SATU - 45.76.146.71
    url: https://45.76.146.71
 - name: IDCLOUD - 103.179.56.126
    url: https://103.179.56.126

status-website:
  cname: check.ezshopnet.com.hk
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/ernawati12968/uptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
